### ISSUE TITLE
Could you please provide the results?

### ISSUE THREAD

**Issue by MarSaKi** [Hoyyyaard/NavGPT#1]
Dear author, thanks for your implementation!
I'd like to inquire whether this repo is for NavGPT in continuous environments.
I have run your code in R2R-CE, but found the performance is low (2% SR).
I'm curious whether the implementation is completed and whether this performance is normal. Could you please provide your results?
In addition,  I found the function of using llava for reasoning is not fully implemented. So, I change the LLM to GPT-4，and my launch script is shown below:
![image](https://github.com/Hoyyyaard/NavGPT/assets/24617881/055d5019-9bec-4058-bee2-4ef3abe81265)

**Comment by Hoyyyaard** [comment]
Hi! Thanks for your interesting.
I used this code to reproduce the results on 100 randomly sampled episodes, achieving 11.8% and 8.5% on R2R, and 2.0% and 0.8% on RxR. The original intention of the LLAVA code was to use LLAVA instead of GPT, but the performance was very poor, so it was not released.

**Comment by MarSaKi** [comment]
I see. Thanks for your quick reply!
